var mainImage = document.getElementById("mainImage");
var banjo = document.getElementById("banjo");
var trees = document.getElementById("trees");
var show = document.getElementById("show");
var puppy = document.getElementById("puppy");
var kiss = document.getElementById("kiss");
var festival = document.getElementById("festival");
var dunes = document.getElementById("dunes");
var city = document.getElementById("city");
var beach = document.getElementById("beach");
banjo.addEventListener('click', event => {mainImage.src = "./media/banjo.jpeg"});
beach.addEventListener('click', event => {mainImage.src = "./media/beach.jpeg"});
city.addEventListener('click', event => {mainImage.src = "./media/city.jpeg"});
dunes.addEventListener('click', event => {mainImage.src = "./media/dunes.jpeg"});
festival.addEventListener('click', event => {mainImage.src = "./media/festival.jpeg"});
kiss.addEventListener('click', event => {mainImage.src = "./media/festival.jpeg"});
puppy.addEventListener('click', event => {mainImage.src = "./media/puppy.jpeg"});
show.addEventListener('click', event => {mainImage.src = "./media/show.jpeg"});
trees.addEventListener('click', event => {mainImage.src = "./media/trees.jpeg"});